### ISSUE TITLE
Histogram on the conversion site

### ISSUE THREAD

**Issue by alois-bissuel** [private-attribution/api#21]
Hello,

From reading the doc on [measuring a conversion](https://private-attribution.github.io/api/#measure-conversion), it seems that the caller cannot specify a histogram bucket (ie the bucket is solely determined in the call to saveImpression).
Is this intentional? For the record, in ARA the bucket is decided by doing a bitwise OR of the buckets contribution at impression and conversion ([source](https://wicg.github.io/attribution-reporting-api/#create-aggregatable-contributions)).

Side question (maybe a bit off-topic): I see that the histogram length is also specified in measureConversion. What happens if the index specified in saveImpression is larger than the histogram size? 
Also, will the histogram length be in the clear? If not, how will histograms of various length be merged?

**Comment by benjaminsavage** [comment]
You're correct that as the spec is currently written, the histogram bucket is solely determined by the call the saveImpression. 

At TPAC I did mention the potential of adding conversion-side breakdown keys. The details of that have not yet been specified. A bitwise OR is an interesting approach. An alternative is the Cartesian product of the impression side and conversion side breakdown key.

As for the side question, I think the intention would be for the histogram size to be constant over time. But in the event that the advertiser changes the value specified for the histogram size, there would be a period of time where the histograms are inconsistent. This *should* still be possible to aggregate. The smaller histograms could just contribute zero to all of the buckets they are lacking.

And finally yes, I assume the histogram length would be in the clear.

**Comment by alois-bissuel** [comment]
Thanks for the clear answer!
